const chalk = require('chalk');
const path = require('path');
const fs = require('fs-extra');

const projectDistDir = path.resolve(process.cwd(), './lib/');
const cssFilePath = path.resolve(projectDistDir, './style.css');
const scssFilesPath = path.resolve(process.cwd(), './src/styles');
const faviconFile = path.resolve(projectDistDir, './favicon.png');
const stylesPath = path.resolve(process.cwd(), './styles');

console.log(chalk.cyan('AnyUI after building script is starting...'));

if (fs.existsSync(cssFilePath)) {
  fs.moveSync(cssFilePath, path.resolve(stylesPath, './components.scss'));
  console.log(chalk.green('Useless style files generated by vite has been removed.'));
}

if (fs.existsSync(faviconFile)) {
  fs.rmSync(faviconFile);
  console.log(chalk.green('Useless icon files generated by vite has been removed.'));
}

fs.copySync(path.resolve(scssFilesPath), stylesPath);
console.log(chalk.green('Styles has been copied to the lib folder.'));

// modify the index.scss
const indexScssPath = path.resolve(stylesPath, './index.scss');
if (fs.existsSync(indexScssPath)) {
  const indexScssContent = fs.readFileSync(indexScssPath, 'utf-8');
  fs.writeFileSync(
    indexScssPath,
    indexScssContent.replace('// components inject', "@import './components.scss';"),
  );
  console.log(chalk.green('Main style file has been injected.'));
}
