import chalk from 'chalk';
import fs from 'fs-extra';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as sass from 'sass';

import { getComponentStyles } from './modules/componentStyles.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const vueSrcDir = path.resolve(rootDir, './packages/vue/src');
const vueDistDir = path.resolve(rootDir, './dist/vue');
const faviconFile = path.resolve(vueDistDir, './favicon.png');
const stylesPath = path.resolve(rootDir, './styles');

console.log(chalk.cyan('AnyUI after-build script is starting...'));

await fs.ensureDir(vueDistDir);
await fs.ensureDir(stylesPath);

const resolverTypes = [
  path.resolve(vueDistDir, './packages/resolver/index.d.ts'),
  path.resolve(vueDistDir, './resolver.d.ts'),
].find((filePath) => fs.existsSync(filePath));

if (resolverTypes) {
  await fs.copy(resolverTypes, path.resolve(vueDistDir, './resolver.d.ts'));
  console.log(chalk.green('Resolver dts file generated.'));
}

if (fs.existsSync(faviconFile)) {
  await fs.rm(faviconFile);
  console.log(chalk.green('Useless icon file generated by Vite has been removed.'));
}

await fs.emptyDir(stylesPath);
await fs.copy(path.resolve(vueSrcDir, './styles'), stylesPath);
console.log(chalk.green('Styles have been copied to the root styles folder.'));

const bundledCssFile = (await fsp.readdir(vueDistDir))
  .filter((fileName) => fileName.endsWith('.css'))
  .map((fileName) => path.resolve(vueDistDir, fileName))
  .at(0);

if (bundledCssFile && fs.existsSync(bundledCssFile)) {
  await fs.move(bundledCssFile, path.resolve(stylesPath, './components.scss'), {
    overwrite: true,
  });
  await fs.copy(path.resolve(stylesPath, './components.scss'), path.resolve(stylesPath, './components.css'));
  console.log(chalk.green('Bundled component style file has been moved.'));
}

const indexScssPath = path.resolve(stylesPath, './index.scss');
if (fs.existsSync(indexScssPath)) {
  const indexScssContent = await fsp.readFile(indexScssPath, { encoding: 'utf-8' });
  await fsp.writeFile(
    indexScssPath,
    indexScssContent.replace('// components inject', "@use './components.scss' as *;"),
    {
      encoding: 'utf-8',
    },
  );
  console.log(chalk.green('Main style file has been injected.'));
}

const compileToCss = async (filePaths) => {
  await Promise.all(
    filePaths.map(async (file) => {
      if (!fs.existsSync(file)) {
        return;
      }
      const target = file.replace('.scss', '.css');
      await fsp.writeFile(target, (await sass.compileAsync(file)).css, { encoding: 'utf-8' });
    }),
  );
  console.log(chalk.green('Basic style files have been compiled.'));
};

const collectDirScss = (dirName) => {
  const actualDirPath = path.resolve(stylesPath, dirName);
  if (!fs.existsSync(actualDirPath) || !fs.statSync(actualDirPath).isDirectory()) {
    return [];
  }
  const dirInfo = fs.readdirSync(actualDirPath);
  return dirInfo
    .filter((file) => file.endsWith('.scss'))
    .map((fileName) => `./${dirName}/${fileName}`);
};

await compileToCss(
  ['./index.scss', './theme.scss']
    .concat(
      ['basic'].reduce((res, dirName) => {
        return res.concat(collectDirScss(dirName));
      }, []),
    )
    .map((p) => path.resolve(stylesPath, p)),
);

await getComponentStyles();
